version: '3.4'

services:
  resortforecaster.migrations:
    image: resortforecastermigrations
    build:
      context: .
      dockerfile: src/ResortForecaster.Migrations/Dockerfile
    depends_on:
      - resort-forecaster-database
    networks:
      - resort-forecaster-database-network

  resort-forecaster-database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: resort-forecaster-database
    environment:
      - SA_PASSWORD=Abcd1234!
      - ACCEPT_EULA=Y
      - MSSQL_TCP_PORT=1234
    ports:
      - "1234:1234"
    user: root
    networks:
      - resort-forecaster-database-network
    volumes:
      - resort-forecaster-database-volume:/var/opt/mssql/data
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  resort-forecaster-database-network:
    driver: bridge
volumes:
  resort-forecaster-database-volume:
